name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - snapshot
    steps:
    - uses: actions/checkout@v3
    
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    
    - name: Install dependencies
      run: |
        emacs -batch -l package -f package-initialize \
          --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" \
          --eval "(package-refresh-contents)" \
          --eval "(package-install 'denote)" \
          --eval "(package-install 'projectile)"
    
    - name: Run tests
      run: make test
    
    - name: Run linter
      run: make lint
      if: matrix.emacs_version == '29.1'
    
    - name: Run checkdoc
      run: make checkdoc
      if: matrix.emacs_version == '29.1'

